inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - apps/*/application.rb

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*
