default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: <%= Anyway::Config.for(:development)[:database_adapter] %>
  database: <%= Anyway::Config.for(:development)[:database_name] %>

test:
  <<: *default
  adapter: <%= Anyway::Config.for(:test)[:database_adapter] %>
  database: <%= Anyway::Config.for(:test)[:database_name] %>

production:
  <<: *default
  adapter: <%= Anyway::Config.for(:production)[:database_adapter] %>
  host: <%= Anyway::Config.for(:production)[:database_host] %>
  port: <%= Anyway::Config.for(:production)[:database_port] %>
  user: <%= Anyway::Config.for(:production)[:database_user] %>
  password: <%= Anyway::Config.for(:production)[:database_password] %>
  database: <%= Anyway::Config.for(:production)[:database_name] %>
